WebApp/Controllers/FuenteController.cs
using Models;
using Services;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class FuenteController : Controller
    {
        // GET: Fuente
        [Authorize]
        public ActionResult Index()
        {
            var listado = FuenteService.GetAll();

            return View(listado);
        }


        // GET: Fuente/Details/5
        [Authorize]
        public ActionResult Details(string id)
        {
            var model = FuenteService.GetDetails(id);
            return View("Details", model);
        }

        // GET: Fuente/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fuente/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Fuente Fuente)
        {
            if (ModelState.IsValid)
            {
                FuenteService.Create(Fuente);
                return RedirectToAction("Index");
            }

            //ViewBag.FuenteDNI = new SelectList(FuenteService.GetDetailsAll(), "DNI", "ApyNom", proyecto.Fuente_DNI);

            return View(Fuente);
        }


        // GET: Fuente/Edit/5
        [Authorize]
        public ActionResult Edit(string id)
        {
            var model = FuenteService.GetDetails(id);
            //ViewBag.DNI = new SelectList(FuenteService.GetDetailsAll(), "DNI", "ApyNom");
            return View(model);
        }

        // POST: Fuente/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Fuente Fuente)
        {

            if (ModelState.IsValid)
            {
                FuenteService.Update(Fuente);
                return RedirectToAction("Index");
            }

            return View(Fuente);
        }

        // GET: Fuente/Delete/5
        [Authorize]
        public ActionResult Delete(string id)
        {
            var model = FuenteService.GetDetails(id);
            return View(model);
        }

        // POST: Fuente/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            FuenteService.Delete(id);
            return RedirectToAction("Index");
        }


    }
}

WebApp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApp/Views/Home/About.cshtml
@model Model.Domain.Cliente

@{
    ViewBag.Title = "About";
}

<h2>About</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Condicion_Tributaria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Condicion_Tributaria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Condicion_Tributaria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Domicilio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Domicilio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<div class="jumbotron">
    @if (Request.IsAuthenticated)
    {
        <h1>Hola @Common.CurrentUser.Get.Name</h1>
        <p class="lead">Bienvenido!!!</p>
    }
    else
    {
        @*<h1>Sistema de Gestión de Clientes</h1>*@
        <p class="lead">Inicie Sesión para comenzar.</p>
        <p>
            <a href='@Url.Action("Login", "Account")' class="btn">Iniciar Sesión &raquo;</a>
        </p>
    }
</div>
<div class="row" style="display:inline-flex; flex-wrap:nowrap; justify-content:center">
    @if (Request.IsAuthenticated)
    {
      <div class="col-md-4">
            <h2>Fuentes</h2>
            <p>Gestionar Fuentes</p>
            <p><a class="btn" href='@Url.Action("Index", "Fuente")'>Fuentes &raquo;</a></p>
        </div>
    <div class="col-md-4">
               <h2>Usuarios</h2>
               <p>Creacion de Usuarios.</p>
               <p><a class="btn btn-default" href='@Url.Action("Register", "User")'>Crear Usuario &raquo;</a></p>
               <p>Visualización de Usuarios.</p>
               <p><a class="btn btn-default" href='@Url.Action("Index", "User")'>Visualizar Usuarios &raquo;</a></p>
        </div>
    }
</div>